function f = T_curve_angles_forsym_pw(l,phi,psi,theta)
%T_CURVE_ANGLES_FORSYM_PW
%    F = T_CURVE_ANGLES_FORSYM_PW(L,PHI,PSI,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    05-Sep-2021 16:12:06

t2 = cos(phi);
t3 = cos(psi);
t4 = abs(theta);
t5 = cos(theta);
t6 = sin(phi);
t7 = sin(psi);
t8 = sin(theta);
t10 = 1.0./theta;
t9 = t2.^2;
t11 = t5-1.0;
t12 = (1.0e-4 < t4);
t13 = (t4 <= 1.0e-4);
t14 = t9.*t11;
t15 = t2.*t3.*t6.*t11;
t17 = t2.*t6.*t7.*t11;
t16 = t14+1.0;
t18 = -t14;
t19 = t5+t18;
if (t12)
    t0 = l.*t10.*t2.*t11;
elseif (t13)
    t0 = l.*theta.*t2.*(-1.0./2.0);
else
    t0 = NaN;
end
if (t12)
    t1 = l.*t10.*t6.*t11;
elseif (t13)
    t1 = l.*theta.*t6.*(-1.0./2.0);
else
    t1 = NaN;
end
if (t12)
    t4 = l.*t10.*t8;
elseif (t13)
    t4 = l-(l.*1.0./t10.^2)./6.0;
else
    t4 = NaN;
end
f = reshape([t17+t3.*t16,t15+t7.*t19,t2.*t3.*t8+t6.*t7.*t8,0.0,t15-t7.*t16,-t17+t3.*t19,-t2.*t7.*t8+t3.*t6.*t8,0.0,-t2.*t8,-t6.*t8,t5,0.0,t0,t1,t4,1.0],[4,4]);
